version: '3'
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:80
    environment:
      - DEBUG=${DEBUG}
      - ACCOUNT_USERNAME=${ACCOUNT_USERNAME}
      - ACCOUNT_PASSWORD=${ACCOUNT_PASSWORD}
      - MONGO_DB=${MONGO_DB}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
    depends_on:
      - mongo
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    volumes:
      - ./app:/code/app
      - ./logs:/code/logs
      - ./docker-logs:/var/log
  mongo:
    image: mongo
    ports:
      - 27018:27017
    volumes:
      - ./data:/data/db