version: '3'
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:80
    environment:
      - DEBUG=${DEBUG}
      - ACCOUNT_USERNAME=${ACCOUNT_USERNAME}
      - ACCOUNT_PASSWORD=${ACCOUNT_PASSWORD}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
    depends_on:
      - mongo
    volumes:
      - ./app:/code/app
  mongo:
    image: mongo
    ports:
      - 27018:27017
    volumes:
      - ./data:/data/db