version: '3'
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:80
    environment:
      - ACCOUNT_USERNAME=${ACCOUNT_USERNAME}
      - ACCOUNT_PASSWORD=${ACCOUNT_PASSWORD}
    depends_on:
      - mongo
    volumes:
      - ./app:/code/app
  mongo:
    image: mongo
    ports:
      - 27018:27017
    volumes:
      - ./data:/data/db
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile

    # Add other configurations for your scheduler service
