version: '3'
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 81:80
    depends_on:
      - mongo
    volumes:
      - ./app:/code/app
  mongo:
    image: mongo
    ports:
      - 27018:27017
    volumes:
      - ./data:/data/db